### ISSUE TITLE
Error in Latex rendering

### ISSUE THREAD

**Issue by Gabriel439** [sdiehl/write-you-a-haskell#57]
I get *[Math Processing Error]* everywhere there is supposed to be (I guess) LaTeX.  It looks like this:

![screen shot 2015-02-28 at 9 46 00 am](https://cloud.githubusercontent.com/assets/1313787/6427216/c852a52a-bf2e-11e4-9f7b-fafbce92d8aa.png)

I'm not sure if this is an issue with my browser (Firefox on OS X) or something else

**Comment by sdiehl** [comment]
It loads MathJax from CDN: http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

If that URL isn't working then all math will not render. At least one other person had this issue and it was caused by an overzealous corporate firewall.

**Comment by sdiehl** [comment]
Does the MathJax example work: http://cdn.mathjax.org/mathjax/latest/test/sample-tex.html ?

**Comment by Gabriel439** [comment]
That MathJax example worked for me

**Comment by sdiehl** [comment]
I don't know how to reproduce the problem. The Mathjax seemingly works for everyone else, so maybe there's something different about your browser or ad-blocking software. Can paste the Javascript error log here, but if there is a MathJax + Firefox bug it's probably best to report it upstream because I wouldn't know how to interpret it.

https://github.com/mathjax/mathjax

**Comment by Gabriel439** [comment]
Alright, then you can close this issue.  It's almost certainly an issue with my setup as other computers of mine can view the math just fine
